### ISSUE TITLE
Plans for upcoming releases

### ISSUE THREAD

**Issue by ljfa-ag** [TeamTotemic/Totemic#126]
This list is mainly so that I don't forget which changes and ideas I want to implement soon. Comments and discussions are welcome though :)

In no particular order:
- [ ] Separate common from NeoForge-specific code to facilitate the Fabric port
- [ ] Update to Minecraft 26.1.2
- [ ] Implement lazy baking of Totem Pole models (to avoid baking lots of wood type-carving-combinations that are never used)
- [x] Refactor and simplify parts of the API, especially for Totem Effects
- [x] Add more customizability via data packs, configs or events
  - [x] Add integration with KubeJS and/or CraftTweaker
- [x] Update to Minecraft 1.20.x (with NeoForge)
- [x] Add config options for disabling some of the Ceremonies (Rain/Drought) (#79)
- [x] Add config option for adding custom wood types (#122)
- [x] Make selecting instruments prefer Totem Bases that are already in selection mode (to make the selection more intuitive when multiple Totem Poles are placed near each other)
- [x] Add Red Cedar hanging signs (to the 1.20.4 version)
- [ ] *Add Red Cedar Boat (textures still missing)*
- [ ] *Improve the music particles (e.g. make them move through the air from source to destination, make them different colors) (postponed)*
- [ ] *Rework the Medicine Bag (maybe make it drain Melody from Totem Poles for charging) (postponed)*
- [ ] *Implement the reworked Totem Pole models made by @VincentLongiug (#108) (postponed)*
