### ISSUE TITLE
Bald Eagle Todo List

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#56]
- [x] Textures (Done)
- [x] Model (Done)
- [x] Sounds (Done)
- [x] Eagle Bone (Done)
- [x] Eagle Bone Whistle (Done)
- [x] Eagle Feathers (Textures done, wiating on @ljfa-ag)

**Comment by Sunconure11** [comment]
Eagle feathers will be done on 1/5/18
